Issue151 integration
nextsimdg/nextsimdg pull request #155
Opened 2022-09-08 11:20 UTC by pminak

2022-09-08 11:29 UTC, timspainNERSC commented
It looks like `ubuntu-latest` is not the latest version of Ubuntu, which does have Eigen 3.4.

Indeed, it is still 20.04LTS `focal`, which only has Eigen version 3.3.7.

2022-09-08 11:40 UTC, timspainNERSC requested changes
I don't think we should include the set(PARENT_SCOPE) commands until they are actually being used.

2022-09-08 11:40 UTC, timspainNERSC commented on dynamics/CMakeLists.txt
> +    "${NextsimSources}"
If you are not (yet) changing the entries in `NextsimSources`, these lines should be removed as redundant. (Also lines 14-16)

2022-09-08 11:40 UTC, timspainNERSC commented on dynamics/src/CMakeLists.txt
> +    "${Sources}"
Again, remove these set( PARENT_SCOPE) commands.

2022-09-16 12:20 UTC, einola commented
Looks like @pminak has addressed the issues raised by @timspainNERSC - right guys?

2022-09-16 12:25 UTC, timspainNERSC commented on dynamics/src/CMakeLists.txt
> +    "${Sources}"
Okay, fine.

2022-09-16 12:25 UTC, timspainNERSC approved these changes

2022-09-23 08:48 UTC, merged