Issue248 doctest
nextsimdg/nextsimdg pull request #253
Opened 2023-03-13 16:09 UTC by timspainNERSC

Replace Catch2 with doctest.

Closes #248

2023-03-23 16:21 UTC, a-smith-github requested changes
Thanks Tim,

This looks a nice swap. Doctest looks like a good call.

Could you expand in the PR about the change you made & it's limitations so we can refer to it later? I've made some assumptions in my review / had to investigate. Also some discussion about including the doctest header here or elsewhere for later reference. Also I don't think the issue captured why the decision to ship a copy of doctest was made, so that should be included here. 

A couple of suggestions/comments (new scheme for test naming and adding description, inclusion of Catch2 in CMake, follow-up issue tracking). 

One more thing. The test output looks like:

===============================================================================
[doctest] test cases:  2 |  2 passed | 0 failed | 0 skipped
[doctest] assertions: 36 | 36 passed | 0 failed |
[doctest] Status: SUCCESS!
[doctest] doctest version is "2.4.10"
[doctest] run with "--help" for options

But could we investigate modifying this so it declares the test name that ran (and the suit name if we go down that route)? --success=true looks overkill maybe leveraging --duration=true (this could also help us track performance regressions going forward).  Also what does a failure look like? --- this should be captured in the PR description / design doc. Obviously this helps diagnosing issues but potentially allows us to track failures better, monitor sporadic issues (which we might start to face more of as we move to multi core and multi process computations and IO), performance issues. 

In general though really happy with doctest & nice work

2023-03-24 08:07 UTC, timspainNERSC commented on CMakeLists.txt
>  find_package(Catch2 REQUIRED)
No, I just missed doing the dynamics/test directory along with the other tests.

2023-03-24 10:38 UTC, timspainNERSC commented on CMakeLists.txt
>  find_package(Catch2 REQUIRED)
Replaced with doctest.

2023-03-24 10:55 UTC, timspainNERSC commented
What does a doctest failure look like?
```
TEST CASE:  ConfiguredAtmosphere melting test

/Users/timpai/nextsim/dg/nextsimdg/physics/test/ConfiguredAtmosphere_test.cpp:137: FATAL ERROR: REQUIRE( qia[0] == doctest::Approx(-83.5952).epsilon(prec) ) is NOT correct!
  values: REQUIRE( -84.5952 == Approx( -83.5952 ) )

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 2 | 1 passed | 1 failed |
[doctest] Status: FAILURE!
```

2023-03-24 12:29 UTC, timspainNERSC commented on core/test/Iterator_test.cpp
> +TEST_CASE("Count iterator testing")
I have wrapped all the TEST_CASEs in a TEST_SUITE (per file) that takes the name of the class under test. To me that reproduces the original functionality, and is sufficient for this PR. Any tests that needs a more detailed description can be added to an issue. (**I** think they're fine.)

2023-03-24 12:34 UTC, timspainNERSC commented on lib/doctest/doctest.h
I have created issue #255 to create a release checklist. Currently the only item is to check and update doctest as necessary.

2023-03-24 16:04 UTC, timspainNERSC commented
You are of course quite right about the doctest LICENSE.txt, which is now included.

2023-03-27 12:10 UTC, a-smith-github approved these changes

2023-03-29 11:42 UTC, merged