WIP: MPI-ify the dynamics
nextsimdg/nextsimdg pull request #663
Opened 2024-08-23 14:17 UTC by TomMelt

Fixes #120 

### Change Description

Text goes here

### Test Description

Text goes here

### Pre-Request Checklist

- [x] Add methods to read halo exchange info into metadata class
- [ ] Add halo exchange info to DGModelArray class
- [ ] Add exchange logic to DGModelArray.hpp

2024-12-04 13:40 UTC, jwallwork23 requested changes
Looks great, thanks @TomMelt. I drew a diagram and convinced myself that the numbers in the CDL files are consistent with the expected values in the tests. I have a couple of suggestions, the main one being a bit of refactoring to avoid duplication.

2024-12-04 13:40 UTC, jwallwork23 commented on core/test/ModelMetadata_test.cpp
> +    }
Could this common part of the tests be pulled out into a function that's called in both places? It'd avoid duplication and reduce the likelihood of human errors when copy/pasting and reviewing.

2024-12-04 13:40 UTC, jwallwork23 commented on core/test/ModelMetadata_test.cpp
> +        // clang-format off
I'm guessing this is because of line length? Might be sufficient to put `using namespace std;` at the top.

2024-12-04 13:40 UTC, joewallwork commented on core/test/ModelMetadata_test.cpp
> +const std::string dateString = "2000-01-01T00:00:00Z";
Unused?

2024-12-05 12:59 UTC, timspainNERSC requested changes
A couple of minor edits.

2024-12-05 12:59 UTC, timspainNERSC commented on core/src/ModelMetadata.cpp
> +        size_t count {}; // number of elements to read from metadata arrays
Initialize numeric types using `= 0`, if indeed that is necessary (`nStart` and `count` seem to be set to other values before being read from).

2024-12-05 12:59 UTC, timspainNERSC commented on core/test/ModelMetadata_test.cpp
> +        // clang-format off
Or define a `typedef` (or `using`)

2025-01-17 14:24 UTC, timspainNERSC commented
Having looked over the changes to ModelMetadata.cpp again, I'm not sure this code should be in there. Perhaps even the grid metadata should be moved out. You don't have to stuff the MPI metadata into existing classes.

Perhaps we should meet to discuss the architecture of the MPI data now that we have more of a handle on what it is going to look like. Possibly including moving the existing coordinate data and functions that are currently in ModelMetadata.

2025-01-17 15:47 UTC, TomMelt commented
> Having looked over the changes to ModelMetadata.cpp again, I'm not sure this code should be in there. Perhaps even the grid metadata should be moved out. You don't have to stuff the MPI metadata into existing classes.
> 
> Perhaps we should meet to discuss the architecture of the MPI data now that we have more of a handle on what it is going to look like. Possibly including moving the existing coordinate data and functions that are currently in ModelMetadata.

@timspainNERSC , yeah that makes sense. I will continue with my halo exchange tests for now and we can sort this before it merges into `develop`

2025-06-04 10:41 UTC, TomMelt commented
This PR has been superseded by #744

2025-06-04 10:41 UTC, closed without merging