ModelArraySlice and slicing infrastructure
nextsimdg/nextsimdg pull request #736
Opened 2024-11-18 13:06 UTC by timspainNERSC

# ModelArraySlice and slicing infrastructure

Fixes #735 

### Task List
- [ ] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [ ] Implemented the source code change that satisfies the tests
- [ ] Documented the feature by providing worked example
- [ ] Updated the README or other documentation
- [ ] Completed the pre-Request checklist below

---
# Change Description

*Please write a summary of the change and specify which Issue this fixes. This should cover the motivation for making the change and provide almost enough context to review the change in isolation. While the issue description is a good place to discuss the failure/requirements, this is the ideal space for explaining why this design fixes the issue and why you designed it the way you did.*

- *If there are important design decisions, particularly those that leverage functionality outside this change or were caused by existing limitations, they should be noted here.*
- *If there is a design specification which relates to this PR, please provide a link to it here.*
- *If the PR relates to an open issue, please link the issue to the PR by using the 'fixes #issue_number' syntax.*
- *If the PR relates to several open issue, make sure to use 'fixes #issue_1, fixes #issue_2, etc.' syntax.*
- *If there are any dependencies (third-party or internal downstream) which are added or impacted, please note them here. And if their limitations informed your design, please note how they did so here (particularly if this information was not captured in a design specification).*

Text goes here

---
# Test Description

*Please describe the tests you have written that verify the enhancement works or that the bug fix has been remedied. For a bug fix, please ensure a complete description of the failure is available here or in the issue such that a reviewer can verify that the testing is suitable. This is a good place to highlight any manual testing you may have had to perform.*

*Please describe any operating system limitations placed on the testing (if appropriate).*

*If your tests fixes any issue, please explain that in the comment you provided in the test file by referencing the issue within the comment and please record the mapping here e.g.*
- *testA fixes issue 404*
- *testB fixes issue 999*

Text goes here

---
# Documentation Impact

*Please describe any changes to the documentation not captured above or, if made in a seperate pull request, please link to the corresponding PR or issue.*

Text goes here

---
# Other Details

*If you have run any static analysis, including complexity analysis, or run coverage testing which has not been captured by an automated tool, please link or copy it here.*

Text goes here

---
### Pre-Request Checklist

- [ ] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [ ] No new warnings are generated
- [ ] The documentation has been updated (or an issue has been created to track the corresponding change)
- [ ] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [ ] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [ ] File dates have been updated to reflect modification date
- [ ] This change conforms to the conventions described in the README

*Please complete your pull request description and delete the instructional text before submitting.*

*Congratulations and thank you for making your contribution to neXtSIM_DG!*

2024-11-19 08:42 UTC, TomMelt commented
just mentioning for future reference... If we move to c++23 we may wish to consider using [`mdspans`](https://en.cppreference.com/w/cpp/container/mdspan). This would allow us to easily switch between 1D and N-D array views.

2025-01-08 14:35 UTC, TomMelt requested changes
@timspainNERSC thanks so much for this functionality. It is really helpful for my halo exchange implementation.

I have been using your slicing class in my current `halo-exchange` branch and it works brilliantly.

Just one issue we have discussed already in the team meeting:

According to my understanding the following slice should work when copy from a sliced ModelArray to a buffer i.e., `ModelArray[Slice].copyToBuffer()`
```cpp
    Slice sliceTop   {{{  },{-1}}}; // unexpected behaviour (-1 doesnt work)
```
But currently it doesn't and I have to use this instead.
```cpp
    Slice sliceTop   {{{  },{ny-1}}};
```

So if possible, my only request is fix the `Slice sliceTop   {{{  },{-1}}};` bug and add a test to the `ModelArraySlice_test.cpp` test.

2025-01-08 14:35 UTC, TomMelt commented on core/src/include/ModelArraySlice.hpp
> +        //        std::cout << this->iter << "!=" << other.iter << "?" << std::endl;
```suggestion
```

Think this was left in by mistake

2025-01-08 14:35 UTC, TomMelt commented on core/src/include/ModelArraySlice.hpp
Could you add docstrings to the methods/functions in this file please?

2025-01-08 14:35 UTC, TomMelt commented on core/src/include/Slice.hpp
> +    Int dimEnd(size_t dim) const
similarly couple of methods/functions here missing docstrings

2025-01-08 14:35 UTC, TomMelt commented on core/src/include/indexer.hpp
similarly missing docstings here

2025-01-08 14:35 UTC, TomMelt commented on core/test/ModelArraySlice_test.cpp
Thanks @timspainNERSC , this test was very helpful for me when planning the halo exchange work. As mentioned in the main review summary, it might be worth adding a test for taking the last row of a 2d structure e.g., the following should work
```cpp
    Slice sliceTop   {{{  },{-1}}}; // unexpected behaviour (-1 doesnt work)
```
But currently it doesn't and I have to use this instead.
```cpp
    Slice sliceTop   {{{  },{ny-1}}};
```

2025-01-13 11:01 UTC, timspainNERSC commented on core/src/include/ModelArraySlice.hpp
> +        //        std::cout << this->iter << "!=" << other.iter << "?" << std::endl;
Removed

2025-01-13 11:02 UTC, timspainNERSC commented on core/src/include/Slice.hpp
> +    Int dimEnd(size_t dim) const
Added docstrings to all public functions and at least some kind of comment to all private ones.

2025-01-13 11:02 UTC, timspainNERSC commented on core/src/include/indexer.hpp
Added docstrings to all public functions and at least some kind of comment to all private ones.

2025-01-13 11:03 UTC, timspainNERSC commented on core/test/ModelArraySlice_test.cpp
This should be fixed now.

2025-01-13 11:46 UTC, timspainNERSC commented on core/src/include/ModelArraySlice.hpp
Added docstrings to all public functions and at least some kind of comment to all private ones.

2025-01-13 12:02 UTC, timspainNERSC commented on core/src/include/indexer.hpp
Added docstrings.

2025-01-15 09:26 UTC, TomMelt approved these changes
Thanks @timspainNERSC. It looks good to me

2025-01-15 09:30 UTC, merged