wip
nextsimdg/nextsimdg pull request #744
Opened 2024-11-25 12:22 UTC by TomMelt

work in progress

2024-11-25 13:00 UTC, joewallwork commented
Note that I changed the logic for determining whether the Docker workflow is run. I an attempt to fix the test failure https://github.com/nextsimhub/nextsimdg/actions/runs/12009927720/job/33475689562 might it be feasible to rebase on top of or merge in `develop`?

Compare https://github.com/nextsimhub/nextsimdg/blob/halo-exchange/.github/workflows/docker.yml vs https://github.com/nextsimhub/nextsimdg/blob/develop/.github/workflows/docker.yml.

2025-01-06 16:05 UTC, TomMelt commented on core/src/include/ModelArraySlice.hpp
> +        auto biter = std::next(buffer.begin(), startIndex);
@timspainNERSC this was a bit hacky from me. I want to populate the buffer but from a specific starting index. Let me know if there's a better way of doing this. 

I was trying to avoid creating temporary arrays for each of the edges.

2025-01-06 16:06 UTC, TomMelt commented on core/src/include/Slice.hpp
> +            // TODO remove me before merging into develop
TODO: remove this before merging this PR. I was using this for debugging purposes

2025-01-06 16:06 UTC, TomMelt commented on core/test/HaloExchange_test.cpp
> +static const bool debug = true;
TODO: change this to `false` before merging

2025-01-28 14:38 UTC, TomMelt commented on core/src/include/Slice.hpp
> +            // TODO remove me before merging into develop
removed

2025-01-28 14:38 UTC, TomMelt commented on core/test/HaloExchange_test.cpp
> +static const bool debug = true;
done

2025-06-04 10:47 UTC, TomMelt commented on core/src/include/ModelArraySlice.hpp
> +        auto biter = std::next(buffer.begin(), startIndex);
this has now been removed as it is no longer needed

2025-06-10 16:35 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +        MPI_Exscan(&numNeighbours[mpiMyRank], &nStart, 1, MPI_INT, MPI_SUM, modelMPI.getComm());
What if we are at rank = 0? This will leave `nStart` uninitialised (and similarly on line 98) due to `MPI_Exscan` computing the exclusive scan.

2025-06-10 16:43 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +
Code after here seems repeated but only the `varName` is changed so this could be refactored to reduce duplication.

2025-06-10 16:45 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +            { 0 }, { static_cast<size_t>(mpiSize) }, &numNeighbours[0]);
I would use `numNeighbours.data()` (https://cplusplus.com/reference/vector/vector/data/) instead of `&numNeighbours[0]` as the latter is technically undefined for empty vectors (which shouldn't happen here but could be a strange edge case!). 
(and then in the other cases which have a similar pattern in the code below).

2025-06-10 17:10 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +        MPI_Exscan(&numNeighbours[mpiMyRank], &nStart, 1, MPI_INT, MPI_SUM, modelMPI.getComm());
Maybe it's fine because nStart is initialized to `0` and so at rank `0` this will just stay at `0`. But I'm not certain that's how MPI_Exscan behaves so might be worth checking (or doing something explicit to be safe).

2025-06-19 10:23 UTC, TomMelt commented on core/src/ModelMetadata.cpp
> +            { 0 }, { static_cast<size_t>(mpiSize) }, &numNeighbours[0]);
Thanks @dorchard , this has been addressed in 786c157b

2025-06-19 10:24 UTC, TomMelt commented on core/src/ModelMetadata.cpp
> +
Thanks @dorchard , hopefully this has been addressed in 786c157b. Let me know if you have any other suggestions.

2025-06-19 10:25 UTC, TomMelt commented on core/src/ModelMetadata.cpp
> +        MPI_Exscan(&numNeighbours[mpiMyRank], &nStart, 1, MPI_INT, MPI_SUM, modelMPI.getComm());
Thanks @dorchard , this has been addressed in 786c157b. It doesn't fix my problems but it is definitely a great addition and makes the code much safer.

2025-06-19 10:42 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +            { 0 }, { static_cast<size_t>(mpiSize) }, &numNeighbours[0]);
Looks good!

2025-06-19 10:42 UTC, dorchard commented on core/src/ModelMetadata.cpp
> +        MPI_Exscan(&numNeighbours[mpiMyRank], &nStart, 1, MPI_INT, MPI_SUM, modelMPI.getComm());
Ah well worth tying down just in case- thanks! It looks good.

2025-09-01 09:50 UTC, timspainNERSC requested changes
A few changes. Some amount of explanation on what some of the tests are doing, and resolving, or deleting, some TODO comments.

2025-09-01 09:50 UTC, timspainNERSC commented on core/src/ModelMetadata.cpp
> +// rename
Either do the renaming or get rid of this comment.

2025-09-01 09:50 UTC, timspainNERSC commented on core/test/HaloExchangeCB_test.cpp
Could add a comment on what is tested within this file. And how it differs from the `HaloExchangePB` test.

2025-09-01 09:50 UTC, timspainNERSC commented on core/test/HaloExchangePB_test.cpp
Could add a comment on what is tested within this file. And how it differs from the HaloExchangeCB test.

2025-09-01 09:50 UTC, timspainNERSC commented on dynamics/src/ParametricMesh.cpp
> +    // TODO check do we need to make any additional changes here
This sounds like a thing that should be checked before merging.

2025-09-01 15:44 UTC, TomMelt commented on core/src/ModelMetadata.cpp
> +// rename
haha thanks. I think I left it in by mistake. It's now been removed

2025-09-01 15:45 UTC, TomMelt commented on core/test/HaloExchangeCB_test.cpp
great will do. For anyone reading this comment CB = closed boundaries and PB = Periodic Boundaries. But I will update both tests with a comment explaining this.

2025-09-01 15:48 UTC, TomMelt commented on dynamics/src/ParametricMesh.cpp
> +    // TODO check do we need to make any additional changes here
Good point. AFAIK we dont need any changes here any more. Now that the halo exchange logic has also changed. So I will remove this comment. 

But I will raise an issue for a separate PR to handle what we do for different vertex grids. It is not obvious what the most sensible choice is for vertex points in the halo region.

2025-09-01 15:54 UTC, TomMelt commented on dynamics/src/ParametricMesh.cpp
> +    // TODO check do we need to make any additional changes here
issuse #923 has been raised.

2025-09-01 17:50 UTC, TomMelt commented on core/test/HaloExchangeCB_test.cpp
Add description in dc5d3208

2025-09-01 17:50 UTC, TomMelt commented on core/test/HaloExchangePB_test.cpp
Add description in dc5d3208

2025-09-18 08:12 UTC, jwallwork23 requested changes
Nice that function signatures are more consistent between the MPI and non-MPI cases with this change.

I've not gone through all of the new test code but I have a few comments and requests on the source code and changes to the XIOS tests.

I think some of the changes you made to `ParaGridIO.cpp` need to be reflected in `ParaGridIO_Xios.cpp`, but that's my problem, not yours. I'm working on the relevant bits of code in #916 and #917 anyway.

2025-09-18 08:12 UTC, joewallwork commented on core/test/XiosDomain_test.cpp
It looks like you reintroduced this file that'd previously been removed? Was this for a reason?

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
I think this section could benefit from some comments to say why `X`, `Y`, `XVERTEX`, and `YVERTEX` are being treated in a particular way.

Also note that the two conditionals could be merged.

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +            // need to figure out what happens w.r.t to coords in non-periodic and periodic case
Will this be done in this PR or a subsequent one?

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
See comment above.

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
As above.

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
Again.

2025-09-18 08:12 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
Same applies here - this isn't clear.

2025-09-18 08:12 UTC, joewallwork commented on core/src/ModelMPI.cpp
> + */
This could benefit from some `@brief` and `@details`.

2025-09-18 08:12 UTC, joewallwork commented on core/src/include/Halo.hpp
> + */
This could benefit from some `@brief` and `@details`.

2025-09-18 08:12 UTC, joewallwork commented on core/src/include/ModelMetadata.hpp
> +    }
It looks like you put the default `partitionFile = ""` because the `partitionFile` argument only gets used the first time you call `getInstance`. However, I doubt `""` will work as a partition filename and will likely raise an error that may or may not have a helpful message. Do we not need to add a catch for this?

2025-09-18 08:12 UTC, jwallwork23 commented on core/test/ConfigOutput_test.cpp
> +#include "ModelMPI.hpp"
`ModelMPI.hpp` included twice.

2025-09-19 09:16 UTC, TomMelt commented on core/test/XiosDomain_test.cpp
Ahh apologies @jwallwork23 . I think this must have snuck back in during the mega merge :scream: ... It was an accident. I can remove it.

I am assuming you dont need it either?

2025-09-19 09:34 UTC, joewallwork commented on core/test/XiosDomain_test.cpp
No worries. If you could just revert the add here that'd be great.

2025-09-19 11:27 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +#endif
Good point. I have added a description and I made a utility function to simplify the logic and make it a bit easier to understand (see commit 03405a0e)

2025-09-19 11:29 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +            // need to figure out what happens w.r.t to coords in non-periodic and periodic case
sorry Tim had already pointed this out and I did remove it. I think the rebase brought it back.

Removed in 6bf80537

2025-09-19 11:30 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +#endif
fixed in f38263bf

2025-09-19 11:30 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +#endif
fixed in https://github.com/nextsimhub/nextsimdg/commit/03405a0ee222f5606ac79575f1ed3328fcf08814

2025-09-19 12:40 UTC, TomMelt commented on core/test/XiosDomain_test.cpp
9ebbb9cd

2025-09-19 12:42 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +#endif
fixed in f38263bf

2025-09-19 12:42 UTC, TomMelt commented on core/src/ParaGridIO.cpp
> +#endif
fixed in f38263bf

2025-09-19 12:47 UTC, TomMelt commented on core/test/ConfigOutput_test.cpp
> +#include "ModelMPI.hpp"
769b0e0d (school boy error :disappointed: )

2025-09-19 12:52 UTC, TomMelt commented on core/src/ModelMPI.cpp
> + */
good point. I will write one for this, `Halo` and `ModelMetadata`. Just a very minor question. Do you think it should be in the `.hpp` file or the `.cpp`. I feel it should go in the `.hpp` because that's like the overview and `.cpp` is the implementation. For Halo there's only the `.hpp` so it doesn't matter. But just curious in general. (Also somewhere is better than nowhere currently :sweat_smile: )

2025-09-19 12:55 UTC, TomMelt commented on core/src/include/ModelMetadata.hpp
> +    }
Good point. I will add a `std::runtime_error` for empty strings. Because NetCDF has a horrible habit of not reporting any useful errors when the file is there, it would be good for me to put a standard c++ "check if file exists" and raise error if not. That way even if the name isn't empty, it still needs to exist. I have been stung too many times but the partition file not existing :sweat_smile:

2025-09-19 14:26 UTC, jwallwork23 commented on core/src/ModelMPI.cpp
> + */
Hm good point. I don't actually know which one (if any) Doxygen picks up. The XIOS one has it in both but maybe we should put it in the headers more consistently.

2025-09-19 14:27 UTC, joewallwork commented on core/src/ParaGridIO.cpp
> +#endif
Thanks, this makes it much clearer :+1:

2025-09-22 08:26 UTC, timspainNERSC approved these changes

2025-09-29 14:08 UTC, TomMelt commented on core/src/include/ModelMetadata.hpp
> +    }
fixed in 6fd44c5e

2025-09-29 14:46 UTC, TomMelt commented on core/src/include/ModelMetadata.hpp
> +    }
had to move it to a different place because it breaks when you use the singleton (see 1830de1b)

2025-09-29 14:57 UTC, TomMelt commented on core/src/ModelMPI.cpp
> + */
I have added doxygen info to  `Halo`, `ModelMPI` and `ModelMetadata` ae334ca9

2025-10-01 09:11 UTC, jwallwork23 requested changes
Thanks for all your hard work on this, @TomMelt! It mostly looks great but I have a few minor requests - mostly related to docs and rewording. Then it should be good to go.

I also have a few suggestions for code changes to ease understanding and reduce duplication but I think they can wait until after this is merged.

2025-10-01 09:11 UTC, joewallwork commented on core/test/ConfigOutput_test.cpp
> +            topMelt(i + 1, j + 1) = 0.6 + 0.01 * (j * nx + (i + offsetX));
I assume the shift-by-1 of index was intentional to only set the interior points? Might be worth a comment.

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> + * @details
Empty details?

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> +     * - Sets up inner and outer slices for Bottom, Right, Top, Left edges
This part could be under `@details`.

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> +        // need send / recv buffers for each componenet (e.g., each DGCOMP)
```suggestion
        // need send / recv buffers for each component (e.g., each DGCOMP)
```

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> +     * @ details this is not intended to be used manually. It should only be called as part of the
```suggestion
     * @details this is not intended to be used manually. It should only be called as part of the
```

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> +     * @ details this is not intended to be used manually. It should only be called as part of the
```suggestion
     * @details this is not intended to be used manually. It should only be called as part of the
```

2025-10-01 09:11 UTC, joewallwork commented on core/src/include/Halo.hpp
> +                }
This duplication could be reduced by giving `ModelMetadata` getters that can say periodic or not but let's leave it for another time.

2025-10-01 09:11 UTC, joewallwork commented on core/test/HaloExchangeCB_test.cpp
I find the test hard to follow because it's difficult to visualise the test data. It's fine to leave it like this for now but might it be possible to refactor later to consider a mesh with fewer data points? Also, we could turn off clang-format to reshape the reference data arrays how their DoFs are distributed spatially.

2025-10-01 09:11 UTC, joewallwork commented on core/test/HaloExchangePB_test.cpp
Similarly for this test.

2025-10-01 09:11 UTC, joewallwork commented on core/test/ModelMetadataCB_test.cpp
> + */
Would benefit from some info about what the test does.

2025-10-01 09:11 UTC, joewallwork commented on core/test/ModelMetadataPB_test.cpp
> + */
And here.

2025-10-01 09:11 UTC, joewallwork commented on core/test/ParaGrid_test.cpp
> +    // Hfield's, DGField and mask
```suggestion
    // HFields, DGField and mask
```
for consistency

2025-10-01 09:11 UTC, joewallwork commented on core/test/ParaGrid_test.cpp
> +    // populate model arrays with dummy data
Suggestion to use 'placeholder', 'stub', or 'sample' rather than 'dummy' (https://www.phoronix.com/news/LF-AOUSD-AWSF-Inclusive-Naming)

2025-10-01 09:11 UTC, joewallwork commented on core/test/ParaGrid_test.cpp
> +    // populate model arrays with dummy data
And here

2025-10-02 08:29 UTC, TomMelt commented on core/src/include/Halo.hpp
> + * @details
woops this was added by mistake. The details are at the top of the file. I have removed this.

2025-10-02 08:29 UTC, TomMelt commented on core/src/include/Halo.hpp
> +        // need send / recv buffers for each componenet (e.g., each DGCOMP)
thanks for spotting. It's fixed now.

2025-10-02 08:34 UTC, TomMelt commented on core/test/ConfigOutput_test.cpp
> +            topMelt(i + 1, j + 1) = 0.6 + 0.01 * (j * nx + (i + offsetX));
Thanks added :ok_hand:

2025-10-02 08:40 UTC, TomMelt commented on core/test/ModelMetadataCB_test.cpp
> + */
Thanks see 231126c0

2025-10-02 08:46 UTC, jwallwork23 approved these changes
Thanks for addressing those @TomMelt. Let's merge it! :partying_face:

2025-10-02 09:31 UTC, merged