Set up `ParaGridIO_Xios` as a copy of `ParaGridIO` for now
nextsimdg/nextsimdg pull request #758
Opened 2024-12-09 17:03 UTC by jwallwork23

# Set up `ParaGridIO_Xios` as a copy of `ParaGridIO` for now

Towards #552
Refinement of #751

### Task List
- [ ] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [ ] Implemented the source code change that satisfies the tests
- [ ] Documented the feature by providing worked example
- [ ] Updated the README or other documentation
- [ ] Completed the pre-Request checklist below

---
# Change Description

This PR creates a `ParaGridIO_Xios` class for us to work on, but just copies what's in `ParaGridIO` for now. This means that we can convert the functionality to use XIOS piece by piece, rather than doing it all at once.

---
# Test Description

CMake for the tests needed to be reordered so that XIOS includes can be picked up. `undef INFO` is added in `ParaGrid_test` to avoid a redefinition warning.

---
### Pre-Request Checklist

- [ ] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [ ] No new warnings are generated
- [ ] The documentation has been updated (or an issue has been created to track the corresponding change)
- [ ] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [ ] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [ ] File dates have been updated to reflect modification date
- [ ] This change conforms to the conventions described in the README

*Please complete your pull request description and delete the instructional text before submitting.*

*Congratulations and thank you for making your contribution to neXtSIM_DG!*

2024-12-10 10:21 UTC, timspainNERSC reviewed
I'd suggest instead using conditional inclusion in `ParaGirdIO.hpp` if the non-XIOS and XIOS versions of that header need to diverge.

2024-12-10 10:21 UTC, timspainNERSC commented on core/src/CMakeLists.txt
> +
Posibbly add the `.cpp` suffix here to make it clear this is a source file.

2024-12-10 10:21 UTC, timspainNERSC commented on core/src/include/ParaGridIO_Xios.hpp
What are the expected differences between the current and `_Xios` versions of the header? Keeping the same header name would mean a lot of the changes in this PR would be unnecessary. If the header does need to change, one option would be to create both `ParaGridIO_NoXios.hpp` and `ParaGridIO_Xios.hpp` with the actual header info in, and to have `#ifdef #include` statements include the correct file.

2024-12-10 10:50 UTC, joewallwork commented on core/src/CMakeLists.txt
> +
Addressed in 1291ae453cfc581d90c42d677709715070466f1e.

2024-12-10 10:51 UTC, jwallwork23 commented on core/src/include/ParaGridIO_Xios.hpp
Great point! There will be parts of it that are needed by one implementation and not the other, but we can start out with selective `#ifdef`s and consider splitting if they diverge too far.

Addressed in 1291ae453cfc581d90c42d677709715070466f1e.

2025-01-08 17:18 UTC, TomMelt approved these changes
Thanks @jwallwork23 . Tested locally and it all seems fine. I think it also satisfies the requirement of 

> - [ ] no new warnings generated 

I didn't get any at least.... am I missing something?

2025-01-13 16:06 UTC, timspainNERSC requested changes
Revisit the way the source file is chosen in the `CMakeLists.txt`.

2025-01-13 16:06 UTC, timspainNERSC commented on core/src/CMakeLists.txt
I think that rather than the rather clunky if … set … dereference chain currently implemented, it might be cleaner set a `ParaGridIOImplSource` variable and add that as another option to `NextsimSourcesTemp`.

```
if(ENABLE_XIOS)
  set(ParaGridIOImplSource "ParaGridIO_Xios.cpp")
else()
  set(ParaGridIOImplSource "ParaGridIO.cpp")
endif()
```
…
```
set(NextsimSourcesTemp
 "${BaseSources}"
 "${NextsimSources}"
 "${ModuleSources}"
 "${ParaGridIOImplSource}"
)
```

2025-04-08 12:06 UTC, jwallwork23 commented on core/src/CMakeLists.txt
How does this look? 950f703a8e4df094aa997a2be8462659965a190d

2025-04-08 12:07 UTC, jwallwork23 commented
> Thanks @jwallwork23 . Tested locally and it all seems fine. I think it also satisfies the requirement of
> 
> > * [ ]  no new warnings generated
> 
> I didn't get any at least.... am I missing something?

Thanks @TomMelt, not sure what this was about because I don't see any warnings either. Marked it as done!

2025-04-29 08:52 UTC, timspainNERSC requested changes
Check whether the include guards in the .cpp files are really necessary. They may be, and I am just missing something.

2025-04-29 08:52 UTC, timspainNERSC commented on core/src/ParaGridIO.cpp
> +#ifndef USE_XIOS
If we are only including this source file when building without XIOS, why do we need the include guards here and in `ParaGridIO_Xios.cpp`?

2025-04-29 10:28 UTC, jwallwork23 commented on core/src/ParaGridIO.cpp
> +#ifndef USE_XIOS
Fair point, thanks @timspainNERSC. Addressed in 3463c41379d5d3c22f4f6de8f3680724153d544d and 672da0937350ad24ad48b10bce2b7e2f4b3a3b8a.

2025-04-29 10:31 UTC, jwallwork23 commented
Ah, with this PR we have an issue that the repo settings expect the `test-ubuntu-mpi` action to pass, but it's been split out into `test-ubuntu-mpi-noxios` and `test-ubuntu-mpi-xios`. So we'll need to edit the repo settings in order to merge it.

2025-05-06 10:45 UTC, timspainNERSC approved these changes

2025-05-06 10:54 UTC, merged