New module system
nextsimdg/nextsimdg pull request #83
Opened 2022-02-21 07:18 UTC by timspainNERSC

Python free and more self-contained.

Will close #59 and #82.

2022-02-21 07:22 UTC, timspainNERSC commented
Well, python free in the important sense. I am writing a script to auto generate the boiler-plate heavy module class files.

2022-03-04 13:43 UTC, einola requested changes
Looks good to me. But I miss that README file. There should still be one to tell developers how to develop a new module.

2022-03-04 13:43 UTC, einola commented on core/src/modules/README.md
> -# ModuleLoader
Don't we still want a README here?

2022-03-04 13:56 UTC, timspainNERSC commented on core/src/modules/README.md
> -# ModuleLoader
Almost certainly.

2022-03-11 07:32 UTC, einola approved these changes

2022-03-11 07:37 UTC, merged